hibernate:
  physical_naming_strategy: tr.gov.anayasa.config.LowerCaseNamingStrategy
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/anayasa
    username: anayasa
    driver-class-name: org.postgresql.Driver